### ISSUE TITLE
Performance: Lag when dragging/moving blocks

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#36] opened 2020-07-02 18:45 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/507.
There seems to be a fairly large amount of lag while a block is moving for a normally high performing platform (Windows 10 + Chrome). The lag seems to show up especially strongly when multiple blocks are moving. To see this, you need to stack blocks and start dragging the bottom one. Falling and pushed blocks also contribute to this. Easiest to see on second or third screen due to larger number of blocks.

**Visuals**
![jarringdrag](https://user-images.githubusercontent.com/41024075/86397693-8b1cee00-bc61-11ea-82c8-2ab87cb049d6.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment] 2020-07-30 15:26
I'm curious if this is still happening (or worse) due to getting rid of reflection computation cost but also adding friction iterations. Can you test https://phet-dev.colorado.edu/html/density/1.0.0-dev.13/phet/density_en_phet.html?

I'm unable to reproduce this on latest Chrome on Win10 or Mac.

**Comment by KatieWoe** [comment] 2020-07-30 18:12
I am still seeing a bit of lag, though it seems better than it was before. I also noticed that my computer was running slow and while it was, the lag on moving blocks was particularly bad. I restarted my computer, which improved things, but some lag was still seen. Win 10 Chrome.

**Comment by jonathanolson** [comment] 2020-08-04 23:01
https://phet-dev.colorado.edu/html/density/1.0.0-dev.14/phet/density_en_phet.html should have a lot of work done for memory leaks, which may help. I'm also curious about https://phet-dev.colorado.edu/html/density/1.0.0-dev.14/phet/density_en_phet.html?p2FrictionIterations=10, which should reduce the friction iterations.

It appears the large majority of CPU time is spent in the physics solve.

@KatieWoe, since I can't reproduce, can you briefly test the above two links to see how they fare?

**Comment by KatieWoe** [comment] 2020-08-07 23:01
Win 10 Chrome. Both links were better than before. Both had a bit of lag still, but it was noticeably better. The second link was the better of the two lag wise.

**Comment by DianaTavares** [comment] 2021-03-23 00:35
I can not reproduce this behavior in the sim version: https://phet-dev.colorado.edu/html/density/1.0.0-dev.15/phet/density_en_phet.html
closing!

**Closed by DianaTavares** 2021-03-23 00:35 UTC
Labels: type:bug, type:performance
