### ISSUE TITLE
Minor flashing when accessing screen for the first time

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#124] opened 2021-12-14 17:51 UTC
**Test device**
MacBook Air
Also seen on Chromebook and iPad

**Operating System**
12.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/751

In the studio wrapper, when accessing a screen for the first time, the sky briefly flashes black and on the Mystery Screen, a second scale will flash to the right of the first one. The flashing is more severe on the Chromebook and iPad than on the MacBook. 
On Chromebook and on the iPad, the flashing can also be seen when the sim is launched while still on the Home screen from Studio.

This only occurs when accessing a screen for the first time. It doesn't occur after the reset button is pressed. 

**Steps to reproduce**
1. Open Studio, select the Intro Screen (you might see the sky flash black)
2. Select the compare screen--the sky flashes black
3. Select the mystery screen--the sky flashes black and the scale also flashes (except on the iPad)

**Visuals**
In the launched sim on the iPad:

https://user-images.githubusercontent.com/87318828/146052356-82787541-294d-4685-bbf8-0c9ea303655d.mov

In studio on the MacBook: 

![studioflashing](https://user-images.githubusercontent.com/87318828/146052795-73352803-6b34-4ea8-b953-2098afec9d60.gif)

**Comment by kathy-phet** [comment] 2021-12-15 17:13
I am observing this flashing of the brief black background in the sky on the base PhET version of the simulation - doesn't need to be in an iFrame or a wrapper. As Nancy noted, its only flashing the very first time a screen is visited. 

I am on Windows and running in Chrome.

**Comment by Nancy-Salpepi** [comment] 2021-12-15 17:21
I should have gone back and checked that @kathy-phet. On Mac + chrome/safari, I am also seeing the flashing of both the black sky and the scale on the Mystery Screen in the regular sim.

**Comment by arouinfar** [comment] 2021-12-22 17:27
I see a VERY brief flash of black when accessing a screen for the first time. I don't think I would have noticed it without looking for it.

Steps to reproduce
1. Open sim and select any screen from home screen. 
2. Use navbar icons to visit the other 2 screens and the sky will briefly flash black.

@kathy-phet @jonathanolson I don't think this should block the RC and I would consider closing it as wontfix.

**Comment by arouinfar** [comment] 2021-12-22 17:43
@kathy-phet said on Slack:

> I dont think it should block publication

**Comment by Nancy-Salpepi** [comment] 2021-12-24 01:02
For https://github.com/phetsims/qa/issues/758 using MacOS 12.0.1 + safari15, I am also seeing other objects briefly flash when using the initialScreen query parameter.
For example, the wooden block A will briefly flash using initialScreen=1. 

Steps to Reproduce:
1. Add ?initialScreen=1 to the end of the Studio wrapper url
2. Change the material of block A to anything but wood

My video is a more dramatic example, using 2 blocks.

**visuals**
![woodenblockflashes](https://user-images.githubusercontent.com/87318828/147302797-2b265d5a-739e-4415-bc77-f694329b4cf7.gif)

**Comment by jonathanolson** [comment] 2022-01-06 02:04
I don't see an easy way to fix this (haven't identified the cause yet, but would be time-intensive).

**Comment by arouinfar** [comment] 2022-01-06 03:42
I am able to reproduce this easily in macOS 12.0.1 in both Chrome and Safari following the steps in https://github.com/phetsims/density/issues/124#issuecomment-1000591627. However, it appears to be a general issue with `initialScreen` because I was able to reproduce it in ph-scale. The time scale of the flicker was a bit longer in density than in ph-scale, but given that it's a common issue and @jonathanolson's assessment, I recommend we punt on it for the 1.0 release and move this issue to the appropriate common repo.

**Comment by kathy-phet** [comment] 2022-01-06 16:24
@samreid @zepumph - will this be fixed with your longer splash screen approach? is the longer splash screen ready to be in production code?

**Comment by zepumph** [comment] 2022-01-06 18:49
Yes, this is the exact problem that the splash screen issue in https://github.com/phetsims/phet-io/issues/1835

**Comment by samreid** [comment] 2022-01-06 18:55
> Yes, this is the exact problem that the splash screen issue in phetsims/phet-io#1835

This new symptom shows after the sim has fully started up, and when screens change, right?  I'm not sure how it could be caused by https://github.com/phetsims/phet-io/issues/1835

**Comment by zepumph** [comment] 2022-01-06 19:08
Ahh I see that. Sorry I was wrong.

**Comment by kathy-phet** [comment] 2022-01-06 19:15
I was talking about the latest update from @Nancy-Salpepi in this comment: 
https://github.com/phetsims/density/issues/124#issuecomment-1000591627

**Comment by zepumph** [comment] 2022-01-06 19:40
Yes that's right.

**Closed** 2023-04-03 20:57 UTC
Labels: type:bug
