### ISSUE TITLE
Adjusting mass can bounce blocks

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/density#24] opened 2020-06-08 21:09 UTC
**Test Device**

MacBook Air

**Operating System**

macOS 10.15.4

**Browser**

Google Chrome 83.0.4103.97

**Problem Description**

For https://github.com/phetsims/QA/issues/507. Probably related to https://github.com/phetsims/density/issues/19. If you quickly adjust the mass of a block, it can bounce. I find this fun, but it's probably not the desired behavior.

**Visuals**

![issue](https://user-images.githubusercontent.com/60749003/84080736-e24cdd00-a999-11ea-8f36-1c1fb2ef97aa.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jonathanolson** [comment] 2020-08-06 15:44
@DianaTavares what is the ideal desired behavior here?

**Comment by jonathanolson** [comment] 2020-08-06 15:45
Also, if the block shifts in size, it seems like it WOULD need to quickly shift the center-of-mass upward, which would give it upward velocity.

**Comment by DianaTavares** [comment] 2020-08-06 16:49
I think that the behavior show be similar to the Flash version (not big jumps upwards)
![Densiy](https://user-images.githubusercontent.com/26031501/89557484-81465780-d7d8-11ea-8d56-13166cabb346.gif)

I understand that small jumps up when the block grows, or little falling down when a big block change to a smaller size can be perceived in the sim. But no like the one shown in the @muedli gif, because that looks more like a buoyancy force.

I think that what is happening is that when the block is small and the user increases its size fast, a force gendered by hitting the ground provokes that jump upward. 

We don0t have this behavior in the sim.

**Comment by DianaTavares** [comment] 2020-08-06 16:51
If the problem is a force generated by the ground because the block pushes down when it grows up, then probably fixing #19 solves the problem.  

If the problem is the fast movement of the center of mass, how can it b solve?

**Comment by jonathanolson** [comment] 2021-01-06 21:14
This can be both a problem for a standalone block, but also a block that is on other blocks. Additionally, it could happen presumably for blocks UNDER other blocks that are floating (so it's not just a hop up).

So I'm really curious what the desired changes should be, as this seems to be a realistic physical feature. How should this be re-thought of? I don't really want to zero-out the velocity of a manipulated block, since that would make adjusting the mass of any floating block look buggy.

**Comment by DianaTavares** [comment] 2021-01-12 18:19
I find this behavior a distraction.  As @muedli said in the beginning "I find this fun", and I don't would like students to get distracted by this movement that is not related to density. Also, I find it even more strange when denser objects are under the water. 
![density 3.gif](https://images.zenhubusercontent.com/5fc925cacd9489e51df9c54d/66af98a5-da1d-4b09-8b93-02041ea013c1)

I like a behavior similar to the Flash version (not big jumps upwards). But I want to read what @ariel-phet. If it is a hard issue to fix, I know that are other bugs with priority and this really doesn't affect a lot the sim.

**Comment by ariel-phet** [comment] 2021-01-15 00:46
@jonathanolson @DianaTavares -- from the point of view of the physics we are showing (no rotation or such) we are treating the blocks as point masses conceptually.

@jonathanolson I think a potential solution would be to always have the center of mass of the block be at its base (this is for instance how we treat the model in something like balancing act). If you did that, then a block growing or shrinking when it is on a surface should not cause any kind of vertical velocity. Is that a possible model simplification?

**Comment by arouinfar** [comment] 2021-01-15 05:03
I also find the current behavior to be a bit distracting, but I like @ariel-phet's suggested model simplification.

**Comment by jonathanolson** [comment] 2021-04-14 16:34
@arouinfar can you try out the current behavior, to see if this is working well?

**Comment by DianaTavares** [comment] 2021-07-20 22:12
it is working perfectly in this: https://phet-dev.colorado.edu/html/density/1.0.0-dev.16/phet/density_all_phet.html.   Thanks, @jonathanolson!! closing

**Closed by DianaTavares** 2021-07-20 22:12 UTC
Labels: status:ready-for-review, type:bug
