### ISSUE TITLE
Pushing block against wall can force it underground, make it unusable

### ISSUE THREAD

**Issue by muedli** [phetsims/density#39] opened 2020-07-07 21:11 UTC
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.15.5

<b>Browser</b>

Chrome 83.0.4103.106, Safari 13.1.1

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/507. Similar to https://github.com/phetsims/density/issues/19. If you push low mass, high volume block up against a wall, it can be forced underground and made unusable.

<b>Steps to Reproduce</b>

1. Intro screen.
2. Two blocks radio button.
3. Custom blocks.
4. Block A has min mass, max volume.
5. Leave block B as is.
6. Place block A next to wall.
7. Use block B to push block A into wall.

<b>Visuals</b>

![issue](https://user-images.githubusercontent.com/60749003/86842314-3f53b580-c062-11ea-91d4-1b8ee9bd2bd7.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by muedli** [comment] 2020-07-07 21:38
I just noticed that the sim thinks the block is in the water.

![issue](https://user-images.githubusercontent.com/60749003/86845997-84c6b180-c067-11ea-9fe2-167ca1267d6f.png)

**Comment by jonathanolson** [comment] 2020-07-23 15:36
With the new physics tweaks, I'm unable to reproduce this on master. @DianaTavares, can you verify?

**Comment by DianaTavares** [comment] 2020-07-23 16:23
Yes, I can't reproduce it. Closing!

**Closed by DianaTavares** 2020-07-23 16:23 UTC
Labels: type:bug
