### ISSUE TITLE
Block position changes when switching to full screen mode

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#117] opened 2021-11-23 13:54 UTC
**Test device**
MacBook Air (M1 Chip) 
**Operating System**
12.0.1

**Browser**
Chrome and Safari

Also seen on Chromebook 

**Problem description**
For https://github.com/phetsims/qa/issues/738

On the Mystery Screen, blocks placed on or near the scale will end up in the pool when 'Full Screen' is selected in the PhET menu. 

**Steps to reproduce**
Here is an example:
1. In the Mystery Screen. Place the 1a and 1b blocks on the scale
2. Select 'Full Screen'

**Visuals**

![fullscreen](https://user-images.githubusercontent.com/87318828/143036606-d9415b1d-8ba9-4b7a-8312-7e13bd4840ad.gif)
<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.19/phet/density_all_phet.html
Version: 1.0.0-dev.19 2021-11-13 00:28:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Language: en-US
Window: 1204x633
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment] 2021-11-23 13:58
If blocks are placed all the way on the right side, they will also end up in the pool once 'Full Screen' is selected.
This also occurs on the 'Compare Screen' as well.

**Comment by KatieWoe** [comment] 2021-11-23 19:57
On firefox, leaving full screen leaves the sim oddly zoomed in until screens are changed.
<img width="959" alt="switchout" src="https://user-images.githubusercontent.com/41024075/143094774-e4bee44e-629e-4396-9fed-2bdb4b60ec35.png">

**Comment by Nancy-Salpepi** [comment] 2021-11-23 21:08
Using MacBook + Chrome and on the Chromebook, this is what happens in the stand alone sim wrapper:
![standalone](https://user-images.githubusercontent.com/87318828/143127357-c83b482f-d278-446e-90b1-643a921ea90d.gif)

**Comment by jonathanolson** [comment] 2021-12-07 18:23
It looks like this is instantly affecting the aspect ratio, thus instantly moving the invisible barrier and the scale to the right (expectedly applying a force and propelling the blocks).

@arouinfar or @DianaTavares thoughts on alternative behavior?

**Comment by arouinfar** [comment] 2021-12-07 22:30
@jonathanolson could the problem be that we allow the scale to float outside of the dev bounds? Would fixing its position within dev bounds alleviate this issue?

**Comment by jonathanolson** [comment] 2021-12-08 03:22
They are on top of the scale, so probably not. Additionally we run into problems when we don't move the scale (since blocks could get sandwiched).

Constraining blocks to within the dev bounds would fix this (however that sounds not ideal?)

**Comment by KatieWoe** [comment] 2021-12-10 17:58
https://github.com/phetsims/density/issues/117#issuecomment-977099489 looks fixed in dev.20

**Comment by KatieWoe** [comment] 2021-12-10 18:11
Movements of blocks when full screen is turned or window size changes still occurs. This was discussed in design meeting on 12/9/21, but I'm not sure where the decisions were recorded. Here is what it looks like in dev.20
![stillmoving](https://user-images.githubusercontent.com/41024075/145621665-61553700-35ab-47d4-a08a-a60cc660a8cb.gif)

**Comment by Nancy-Salpepi** [comment] 2021-12-10 18:16
@KatieWoe I think what was decided at the meeting yesterday was.. as long as the reset button was still visible, that was OK. @arouinfar said she was going to add to teacher tips.

**Comment by Nancy-Salpepi** [comment] 2021-12-10 19:32
On Mac + safari/chrome, the reset button is always visible when resizing window and when moving to/from full screen mode.

**Comment by markgammon** [comment] 2021-12-15 18:41
@KatieWoe in your screencast above, is the sim's menu bar at the bottom actually getting cut off, or is that just how the screencast is cropped? Want to confirm that going full-screen is not impacting access to the menu/navigation.

**Comment by KatieWoe** [comment] 2021-12-15 20:13
The bottom is not actually being cut off. The window I was using to record didn't catch the new size. Sorry about that.

**Comment by arouinfar** [comment] 2022-01-06 03:55
@jonathanolson I think the changes made in https://github.com/phetsims/density-buoyancy-common/issues/67 have addressed this issue. Switching to full screen may shift the scale/blocks but I am unable to recreate the zoomed-in effect or lose any of the UI elements. I recommend having QA review this issue in the next RC cycle.

**Comment by Nancy-Salpepi** [comment] 2022-01-07 21:21
Forhttps://github.com/phetsims/qa/issues/759:
With Mac + safari/chrome:  When screen aspect ratio is changed, I can still access all of the blocks in the PhET brand sim, PhET-iO standalone and when launching the sim in Studio. I also still have access to all UI components.

Since the blocks still shift locations when changing the screen size, I wasn't sure if I should close this issue. @kathy-phet and @arouinfar is that aspect of the issue something that will be revisited in the future?

**Comment by KatieWoe** [comment] 2022-01-07 21:57
Things seem ok on Win 11 Firefox as well.

**Comment by arouinfar** [comment] 2022-01-07 22:17
Thanks @Nancy-Salpepi @KatieWoe. Since we aren't losing access to blocks or other UI elements, I think we can go ahead and close.

**Comment by KatieWoe** [comment] 2022-01-07 22:36
Reopening as I found a way, at least on Win 11 Chrome, to lose blocks by changing the window size. The window needs to be fairly short and long, and then returned to a taller window fairly quickly with a block outside the new window's frame. This is a bit extreme, but easy enough to do with a short enough window.
![rediculous](https://user-images.githubusercontent.com/41024075/148616151-4809b028-9bb7-4cea-9afe-ead978c23844.gif)

**Comment by jonathanolson** [comment] 2022-01-07 22:39
That may perhaps be related to https://github.com/phetsims/density-buoyancy-common/issues/67, I'm curious what aspect ratios we want to support. There may be some downsides to increasing the "size" of the barrier (which I think would probably solve this)

**Comment by arouinfar** [comment] 2022-01-07 22:51
This looks like a really extreme aspect ratio. I am fine with marking this as wontfix, so long as the blocks return on reset all. 

@KatieWoe can you confirm that blocks are returned on reset all? Also, have you been able to reproduce this without using extreme aspect ratios?

**Comment by KatieWoe** [comment] 2022-01-07 22:53
They are returned on reset all. I've reproduced it with less extreme aspect ratios, but all that I saw were still what I would consider unusual. I'm not sure what the boundary between it happening and not is.

**Comment by arouinfar** [comment] 2022-01-07 23:07
Thanks @KatieWoe. My inclination is to close as wontfix, but add a statement to the Teacher Tips.

@DianaTavares please add this to the Model Simplifications section:

* Sudden changes in the aspect ratio of the simulation can result in blocks being shifted around. In extreme situations, it is possible for blocks to be lost off-screen, but they can be restored with the Reset All button.

**Comment by DianaTavares** [comment] 2022-01-11 19:52
Done!

**Closed by DianaTavares** 2022-01-11 19:52 UTC
Labels: type:bug
