### ISSUE TITLE
User reported issue: water disappears

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/density#11] opened 2020-03-18 14:28 UTC
**Problem description**
In the “Intro” tab the user has the ability to set the density to “Custom.”  If the user sets the mass to zero the block and the pool of water disappear.  The reset button properly returns the water.
**Steps to reproduce**
Just go to custom and adjust the mass to zero.
**Visuals**
At very low density (.03 kg/ 10 L) the mass begins to oscillate through the atmosphere.  I assume this is intended. (and I love it) but I think the density should be a bit lower for this behavior and maybe less dramatic.

**Comment by jonathanolson** [comment] 2020-03-26 18:00
Handling zero-mass custom masses now.

I'm trying to reproduce the "oscillate through the atmosphere", but I'm not sure how. I've gotten that same density custom mass, and it seems to arc normally through the atmosphere.

Thoughts?

**Comment by arouinfar** [comment] 2020-03-26 18:26
@jonathanolson I think I've recreated what the user is talking about.

Steps to reproduce
1. Intro Screen
2. Select custom block
3. Set mass to 0.03 kg. There will be some visible oscillations when the mass gets that low.
4. Increase volume gradually. The mass will start to bounce, eventually escaping dev bounds.

![density](https://user-images.githubusercontent.com/8419308/77682469-9d99d400-6f5c-11ea-9a0c-2042ad747ac6.gif)

I don't see any reason why we should allow users to set the mass to 0.00 kg. The minimum mass for styrofoam is 0.02 kg, so perhaps the lowest Custom mass should be 0.01 kg. I don't notice the strange oscillating behavior at that mass. Thoughts @DianaTavares?

**Comment by DianaTavares** [comment] 2020-03-26 18:32
haha, I was just doing the same but reducing the mass! I agree with @arouinfar With a minimum mass of 0.10 kg is good enough to explore materials with small density. 
![density](https://user-images.githubusercontent.com/26031501/77683144-9a531800-6f5d-11ea-9677-233720445a67.gif)

**Comment by jonathanolson** [comment] 2020-03-26 20:53
Implemented 0.1 minimum mass for those sliders, does the behavior on master look good?

**Comment by arouinfar** [comment] 2020-03-26 21:37
Looks good to me!

**Comment by DianaTavares** [comment] 2020-03-26 23:28
It looks good!!

 But I see one bug. When I move the volume control, the mass also changes. that only happens when I put the minimus mass and then I increase and decrease the mass.  Last time it stops changing when it gets 1 kg, but in the gift only get till 0.3kg

![Untitled](https://user-images.githubusercontent.com/26031501/77706098-09913200-6f87-11ea-9a71-b4da70006876.gif)

**Comment by jonathanolson** [comment] 2020-04-30 16:30
This behavior should now be fixed in master.

**Comment by DianaTavares** [comment] 2020-04-30 19:04
In this issues was discussed three different strange behaviors:
1) The mass goes to zero and the water disappears. That problem was solved correctly!! 

2)Mass oscillations when the density is small. I played with different configurations and now the mass doesn't oscillate with small movements of the volume or mass. The only way that I get a lot of oscillation is with a fast change to the minimus mass:

![density1](https://user-images.githubusercontent.com/26031501/80746350-5b2d5f00-8ae7-11ea-8cd6-c8be579c5cf6.gif)

I find it a little distracting. The example shown in the gif takes 14 seconds to get the equilibrium.  What do you think @arouinfar ? The behavior is much better and I don't know if continue improving this means a lot of work @jonathanolson 

3) The mass still changing by itself when the volume is modified in the custom option. In the gif, I show how the mass increase when it is in the minimus value and the volume is modified, and also how the mass decreases when it is set in the max value and then the volume is decreased. 

![density2](https://user-images.githubusercontent.com/26031501/80747122-8d8b8c00-8ae8-11ea-8b0a-9081a7080478.gif)


extra! 4) I love that now the collision between the invisible walls in the edge of the sim and the blocks in inelastic. Is possible to do the same with the collision blocks to blocks? I the gif I show some examples of collisions. I feel distracting that behavior

![density3](https://user-images.githubusercontent.com/26031501/80748763-0ee41e00-8aeb-11ea-8e49-3f6a6059a040.gif)

**Comment by jonathanolson** [comment] 2020-05-06 20:59
For (2), I increased the viscosity effect for small masses, so things will reach equilibrium much faster.

For (3), I can't reproduce this at all in master. Can you pull on phettest and outline reproduction steps, or see if it's fixed?

For (4) I upped the internal engine "relaxation" for block-block forces to improve this effect.

How do these changes look?

**Comment by DianaTavares** [comment] 2020-05-06 21:26
It looks great! 
I couldn't reproduce (3), Then I think it is fixed. 
Thanks, @jonathanolson. For my side, I see the simulation with good performance and I don't find anything that needs to be fixed. Ready for the next step!!

**Closed by DianaTavares** 2020-05-06 21:26 UTC
Labels: type:bug, type:user-feedback
