### ISSUE TITLE
Zoom feature does not work for 3D portion of the sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/density#50] opened 2020-09-03 23:30 UTC
Noticed that the zoom feature only works on the 2D UI. Disabling zoom in this sim until this can be resolved.

**Comment by jessegreenberg** [comment] 2020-09-09 22:27
From https://github.com/phetsims/joist/issues/659.

**Comment by ariel-phet** [comment] 2020-09-15 02:08
@jonathanolson this would be a desirable sim to have zoom available in when published if easy to work around adjusting the webgl/shader code. If that is a difficult task, let's discuss.

**Comment by jonathanolson** [comment] 2021-03-31 05:49
I'm trying to look into this, but I'm curious how to reproduce. Two-finger gestures don't seem to be triggering this in the sim (but it says it supports pan and zoom), and after scanning things and testing, I don't see an easy way to programmatically trigger this.

**Comment by jessegreenberg** [comment] 2021-03-31 17:15
I just tried the sim on master with macOS 11.2 and I am able to see this by zooming into the sim with the trackpad and using "Command" + "+". Also seeing this on Windows 10 Chrome by zooming in with the keyboard. But zooming into the PhET menu (for example) looks like this for me

<details>

![image](https://user-images.githubusercontent.com/6396244/113184312-04626500-9223-11eb-99f3-05a03113e917.png)
</details>

@jonathanolson let me know if you are still unable to zoom, and maybe platform details if there is a platform where it isn't working correctly?

**Comment by jonathanolson** [comment] 2021-03-31 17:29
I... don't know what I was doing before. First of all, command-+ works perfectly, and the pinch gestures are working. The 3d view is clearly not moving, and I can definitely take it from here. Sorry!

**Comment by jonathanolson** [comment] 2021-03-31 17:31
How should panning work when zoomed in for this simulation? The behavior of "drag the background to rotate the molecule" is getting activated in addition to the panning. @jessegreenberg would it make sense to disable this sim-specific behavior when the sim is zoomed in, but leave it when everything is visible?

**Comment by jessegreenberg** [comment] 2021-03-31 19:13
I assume that question is for molecule-shapes? Panning by dragging the molecule is generally disabled correctly in that sim, but if you drag the molecule close to the edge of the screen it pans to try to keep the molecule in view even though the molecule is fixed in position. I don't think that should happen, and it is an issue with the AnimatedPanZoomListener. I will make an issue to investigate.

**Comment by jessegreenberg** [comment] 2021-03-31 20:34
Ahhh, I see now that you can drag anywhere in the whole background to rotate the molecule. Yes, disabling that when zoomed in (which I think you have implemented) is behaving as I would expect in molecule-shapes. I also reduced the panning that happens during drag which I think makes rotating the molecule behave better when zoomed in. Assigning to back to you @jonathanolson.

**Comment by jonathanolson** [comment] 2021-04-13 01:09
> I assume that question is for molecule-shapes?

Embarrassing. Definitely did. Didn't see an issue there, but it was helpful to solve there first.

I added support for density/buoyancy in general with the above two commits (or any sims using mobius for 3d can pass in the animatedPanZoom listener's matrixProperty into the ThreeIsometricNode).

@jessegreenberg can you verify?

**Comment by jessegreenberg** [comment] 2021-04-13 16:06
OK cool, its working great! I made a note about something happening with the ground in density/buoyancy in https://github.com/phetsims/buoyancy/issues/6#issuecomment-818851562 but that can be tracked there and everything else is working well. This can be closed.

**Comment by jonathanolson** [comment] 2021-04-13 17:10
Opening here so I can track in the Density repo too. Thanks for the catch!

**Comment by jonathanolson** [comment] 2021-04-13 17:16
This is also broken in molecule-shapes.

**Comment by jonathanolson** [comment] 2021-06-16 21:22
Mobius is reworked to handle this. Required a full rewrite of the coordinate math and how we handle full-screen three.js (we're actually showing it full-screen, even behind the navbar, so we avoid the performance penalty of changes). The approach is complicated, but it also removes the need to compute FOVs and handle pan/zoom separately from other concerns. Closing.

**Comment by zepumph** [comment] 2023-01-16 17:27
Looks like there is one more TODO here: 
https://github.com/phetsims/mobius/blob/c5062710ec96a6b9f8f1ec1dd1f7b51452704eea/js/ThreeStage.ts#L321

**Comment by jonathanolson** [comment] 2023-04-04 19:04
Handled, closing!

**Closed by jonathanolson** 2023-04-04 19:04 UTC
Labels: type:bug, priority:3-medium
