### ISSUE TITLE
Sim won't launch after Mystery Screen is accessed 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#87] opened 2021-08-25 21:20 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.4

**Browser**
chrome

**Problem description**
Once the Mystery Screen is accessed, the sim will not load in Studio wrapper. The Home screen appears after the preview sim button is pressed, but sim doesn't load.

**Steps to reproduce**
1. Open Mystery Screen
2. Change to either Explore or Intro screen (even this step can be skipped)
3. Select preview Sim

**Visuals**
<img width="541" alt="Screen Shot 2021-08-25 at 4 46 12 PM" src="https://user-images.githubusercontent.com/87318828/130865781-241ad6e0-b4be-46ec-a738-e4a321fe42ac.png">

**Comment by jonathanolson** [comment] 2021-09-10 00:42
The contact force on the scale seems to immediately go to NaN (not-a-number), and it looks like that's getting nulled out by the JSON stringify (infinities and NaNs don't transfer well to JSON, since they're not supported).

![image](https://user-images.githubusercontent.com/480878/132780349-38b6b8fc-e084-48ae-b34c-07fb49ed8b2e.png)

So first of all, I would expect NumberIO and Vector2IO (etc.) to handle serializing infinities and NaNs. @zepumph should we create a general issue?

But also, I shouldn't be getting NaNs anyway, I'll fix that.

**Comment by jonathanolson** [comment] 2021-09-10 00:53
The p2.js physics engine is reporting the scale's mass at `1.7976931348623157e+308`.

**Comment by zepumph** [comment] 2021-09-11 21:26
We do support infinity in NumberIO, but it looks like Vector2 wasn't using that, see https://github.com/phetsims/dot/issues/110.

https://github.com/phetsims/tandem/issues/246 for general investigation and unit test creation.

**Comment by jonathanolson** [comment] 2021-09-14 16:55
I believe this is fixed in master, can you verify?

**Comment by Nancy-Salpepi** [comment] 2021-09-14 17:25
Preview sim launches perfectly now.

**Comment by Nancy-Salpepi** [comment] 2021-09-14 17:29
@jonathanolson once the sim is launched, the reset button doesn't work in the mystery screen. Shall I open a separate issue?

**Comment by jonathanolson** [comment] 2021-09-15 16:15
@Nancy-Salpepi I'm curious what you're seeing. Some bugginess I'm seeing is:

1. Load studio and go to the mystery screen
![image](https://user-images.githubusercontent.com/480878/133470253-a9294503-71c0-4f6e-bfa4-1ae9f4acd05f.png)

2. Preview sim:
![image](https://user-images.githubusercontent.com/480878/133470324-fb535be0-ff61-4b68-992f-35e706b38efb.png)

The block gets pushed to the side

3. Reset-all
![image](https://user-images.githubusercontent.com/480878/133470423-1b1309a6-a313-4382-b013-03bd129fd3a9.png)

Seems to be "properly" resetting, HOWEVER the scale briefly flashes on the left side, and the E block flashes in the middle.


I'm not seeing a blanket "reset all doesn't work" case, can you clarify? (I'm working to resolve the above issues)

**Comment by Nancy-Salpepi** [comment] 2021-09-15 16:41
@jonathanolson this is what I did:
1. In studio, I selected the Mystery Screen
2. I placed the 1b and 1a blocks in the water
3. I pressed "Preview Sim"
4. In the launched sim, I pressed the reset button--I see the same flashing that you described, but also the blocks stay in the water. 

![noreset](https://user-images.githubusercontent.com/87318828/133474453-421215de-108e-48ef-b795-87e6541f7ffc.gif)

**Comment by jonathanolson** [comment] 2021-09-15 20:33
I believe this should be handled in master, can you verify?

**Comment by Nancy-Salpepi** [comment] 2021-09-16 19:52
Hi Jonathan 
Everything resets as it should but the 1E block still flashes. I no longer see the scale flashing.

**Comment by samreid** [comment] 2021-09-25 21:48
I was able to reproduce the problem, but not familiar enough with the sim to make progress on my own.  I invited @jonathanolson on slack to schedule an appointment where I can be more helpful.  Unassigning for now.

**Comment by jonathanolson** [comment] 2021-09-29 16:54
Finally tracked down the 1E flash, can you verify that the above commit fixes it?

**Comment by jonathanolson** [comment] 2021-09-29 16:54
(Should be fixed in master)

**Comment by Nancy-Salpepi** [comment] 2021-09-29 17:17
@jonathanolson--the 1E block no longer flashes. Unfortunately, the 1A and 1B are now flashing. 

I followed the same steps as before using my MacBook Air OS 11.6 + chrome:
1. In studio, select the Mystery Screen
2. Place the 1b and 1a blocks in the water
3. Press "Preview Sim"
4. Move some blocks around and then press "reset"  OR Just press "reset" without moving anything. 

![1abblocksflashing](https://user-images.githubusercontent.com/87318828/135317500-01d12134-d64f-4985-a84a-6ac997b91eae.gif)

**Comment by Nancy-Salpepi** [comment] 2021-09-29 17:21
Also, if I then add this step:
5. move to the Compare Screen and press the "reset" button

the yellow block flashes above the water

**Comment by jonathanolson** [comment] 2021-09-29 20:02
Can you try master now with the above commits?

**Comment by Nancy-Salpepi** [comment] 2021-09-29 20:39
The situation is much improved. I am no longer seeing the entire box flashing. Instead, there is just a small flash sometimes when reset is pressed. Note the flashing next to the 1c and 1e labels:



![flashingnextto1c](https://user-images.githubusercontent.com/87318828/135345017-6e443b73-2d77-49ce-8c39-8372bc9cd1b7.gif)

**Comment by jonathanolson** [comment] 2021-09-29 23:15
@DianaTavares let me know the severity of the above issue? It may take a while to solve.

**Closed as completed** 2021-10-14 06:58 UTC
Labels: type:bug, type:wontfix

**Comment by Nancy-Salpepi** [comment] 2021-12-28 13:37
Hi @jonathanolson and @arouinfar. I know it was decided to close this issue and leave the slight flickering seen in https://github.com/phetsims/density/issues/87#issuecomment-930526195 as won't fix. 
I just wanted to let you know that this flickering is also seen in the Input Record and Playback wrapper and Record/Playback wrappers as well. I didn't know if what I am seeing is severe enough to reopen or not. 

mac + chrome, input record and playback wrapper:
![mirrorflashing](https://user-images.githubusercontent.com/87318828/147570381-b68223cf-75b5-4255-bb00-c958e9dd715f.gif)

Mac + firefox, playback wrapper:
![playbackblockflash](https://user-images.githubusercontent.com/87318828/147571361-9e155a88-0051-43d2-a269-4c91cae78e2d.gif)
