### ISSUE TITLE
Weighing bug

### ISSUE THREAD

**Issue by lesha724** [phetsims/density#194] opened 2024-03-15 14:01 UTC
Hello, I have bug with weight in mystery section:

![image](https://github.com/phetsims/density/assets/8524434/0811cc2b-b29e-4436-8f1d-92128044f741)
![image](https://github.com/phetsims/density/assets/8524434/b3abd38d-5e24-44d4-bec8-586fe7ffbb04)
![image](https://github.com/phetsims/density/assets/8524434/7791c350-7ced-424c-99a0-d11ae4cd70b8)
![image](https://github.com/phetsims/density/assets/8524434/b2324857-241c-4097-bf3b-a9c2f0d4084a)
![image](https://github.com/phetsims/density/assets/8524434/5e253687-7229-457e-b6c7-6608a8de0d6e)

**Comment by zepumph** [comment] 2024-03-15 17:39
Thanks for the submission. I will take a look and bring it to my team.

**Comment by zepumph** [comment] 2024-03-15 20:47
This may be related to https://github.com/phetsims/buoyancy/issues/64

**Comment by zepumph** [comment] 2024-04-13 00:04
I was able to reproduce the problem. I can see that the value can change depending on how I drop the top block onto the bottom one. I sometimes got a value like: 19.704819877536927, and other times, 19.70501456941877. I will see if it is just a dividing error slop, or if it is in part from some of the tolerances built into the P2 physics engine. If it is the latter, we may decide not to change this, since values for stiffness/relaxation/etc have been fine tuned to fix many other bugs (see [here](https://github.com/phetsims/density-buoyancy-common/blob/4d5609c071c4a270755bbecf60f5a74532eb3c0f/js/common/DensityBuoyancyCommonQueryParameters.ts#L64-L172)).

**Comment by AgustinVallejo** [comment] 2024-05-21 18:15
We're experimenting with a solution for https://github.com/phetsims/buoyancy/issues/64 that might affect this. On hold

**Comment by AgustinVallejo** [comment] 2024-05-30 19:51
https://github.com/phetsims/buoyancy/issues/167 This fix made this issue dissappear as well. Closing

**Comment by zepumph** [comment] 2024-05-31 16:30
This bug was reported by an outside party (thank you for doing that). It isn't clear that we are republishing this sim with the publication of buoyancy, and if not this is still a bug in production. Let's keep this open until confirming that we are planning to republish density also. Otherwise we may consider an MR.

**Closed** 2024-06-03 16:01 UTC
Labels: type:bug, status:on-hold
