### ISSUE TITLE
Dragging a block quickly past a barrier can cause oscillation

### ISSUE THREAD

**Issue by samreid** [phetsims/density#26] opened 2020-06-11 13:57 UTC
When dragging a block quickly past the bottom or side of the pool, it can cause oscillation.  Stacking other blocks on top can create a distracting animation:

![reduced](https://user-images.githubusercontent.com/679486/84393646-118d6500-abb9-11ea-831e-34d2886d1eda.gif)

**Comment by jonathanolson** [comment] 2020-07-30 15:45
It looks like this issue should be resolved with the new physics parameters. I'm not able to reproduce this anymore in master, can you verify?

**Comment by samreid** [comment] 2020-07-30 16:06
I pulled master and disabled cache, and I am seeing this behavior:

![Kapture 2020-07-30 at 10 06 04](https://user-images.githubusercontent.com/679486/88946327-5befa180-d24c-11ea-897b-5ba1e3556ad0.gif)

**Comment by jonathanolson** [comment] 2020-07-30 16:41
Thanks, investigating!

**Comment by DianaTavares** [comment] 2021-03-23 00:41
I can not reproduce this behavior with the sim version: https://phet-dev.colorado.edu/html/density/1.0.0-dev.15/phet/density_en_phet.html

**Closed by DianaTavares** 2021-03-23 00:41 UTC
